### PR TITLE
handle BOSH req timeout

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by chris-rock** [comment]
looks good

**Comment by sonnyp** [comment]
@chris-rock please next time could you just review? I'll take care of merging + deleting the branch once :+1: 
I'm using those branches in my package.json

**Comment by chris-rock** [comment]
@sonnyp I recommend using private forks until the branches are merged in master and released as version. Personally, I think that the person who adds a PR should not merge a PR. Thats why I haven't merged my own Bosh PR.

**Comment by sonnyp** [comment]
@chris-rock you're right :+1:

**Pull request merged**
