### PR TITLE
allow * and multiple values for CORS origin

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by lloydwatkin** [comment]
@sonnyp apparently there's an issue with latest core (which I think included a PR from you) could you take a look, there's an issue against core for it. Might be related.

**Comment by sonnyp** [comment]
@lloydwatkin are you talking about https://github.com/node-xmpp/node-xmpp-core/issues/63 ?

**Comment by lloydwatkin** [comment]
Yes, I may be wrong about its source though (definitely not trying to proportion blame in any way :))

**Comment by sonnyp** [comment]
@lloydwatkin thanks for the commit, could you next time comment on the PR?

**Pull request merged**
