### PR TITLE
fix a crash with invalid BOSH body

### PR DESCRIPTION
**Pull request by sonnyp**

### CODE REVIEW

**Comment by mllocs** [comment]
:ship: :it: :+1:

**Comment by chris-rock** [comment]
that makes sense ;-)

**Comment by sonnyp** [comment]
@chris-rock let's address this in an other PR but got a question, if an error happens during parsing the body, I'd like it to be emitted somewhere, so that software using node-xmpp-server can log it, where do you think that should be?

**Comment by chris-rock** [comment]
since we only use debug, the best way I see at the moment is to use debug(error) within the error handling block

**Comment by chris-rock** [comment]
I'll merge it, but lets focus on getting back to green tests as soon as possible

**Comment by sonnyp** [comment]
@chris-rock we don't have debug enabled on production

**Comment by chris-rock** [comment]
since we do not want to add a logger dependency, I think we should emit the error event

**Comment by sonnyp** [comment]
@chris-rock agree but on what object?

**Comment by chris-rock** [comment]
the bosh server object?

**Comment by sonnyp** [comment]
I guess ideally it would be on the session object but we don't have the session yet at that point so yeah I guess it only leaves us with the server option. We could use a special error message.

**Pull request merged**
